<template>
  <div>
    <b-container fluid>
      <b-row>

        <b-col cols="4">
          <h2>Grupas pievienošana:</h2>
          <div>
            <b-form-group label-cols="4" label-cols-lg="3" label="Grupas nosaukums:" label-for="input-default">
              <b-form-input id="input-default"></b-form-input>
            </b-form-group>
          </div>
          <div>
            <label for="selected">Specialitate:</label>
            <b-form-select v-model="selected" :options="options"></b-form-select>
          </div>
        </b-col>

        <b-col cols="8">
          <b-table responsive :items="items" :fields="fields" :tbody-tr-class="rowClass">
            <template #cell(functions)="row">
              <b-button size="sm" variant="success" @click="$router.push({ name: 'DocumentView', params: {id: row.item.id} })" class="mr-1">
                Printēt
              </b-button>
              <b-button size="sm" variant="danger" v-b-modal.modal-sm @click="archiveItem(row.item.id, row.index)">
                Dzēst
              </b-button>
            </template>
          </b-table>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>
<script>
export default {
  data() {
    return {

      fields: [
        {key: 'number', label: 'Nr.'},
        {key: 'group_name', label: 'Grupas nosaukums.'},
        {key: 'classification', label: 'Klasifikācija.'},
        {key: 'specialty', label: 'Specialitāte'},
        {key: 'functions', label: 'Funkcijas'},
      ],

      items: [
        { "number": '1.',
          "group_name": 'A1-1',
          "classification": 'Automehāniķis',
          "specialty": 'Autotransports',
          "functions": ''},
        { "number": '2.',
          "group_name": 'A1-2',
          "classification": 'Automehāniķis',
          "specialty": 'Autotransports',
          "functions": ''},
        { "number": '3.',
          "group_name": 'ATK1',
          "classification": 'Transportlīdzekļu krāsotājs',
          "specialty": 'Autotransports',
          "functions": ''},
        { "number": '4.',
          "group_name": 'AV1',
          "classification": 'Autovirsbūvju remontatslēdznieks',
          "specialty": 'Autotransports',
          "functions": ''},
        { "number": '5.',
          "group_name": 'B1',
          "classification": 'Klientu apkalpošanas speciālists',
          "specialty": 'Administratīvie un sekretāra pakalpojumi',
          "functions": ''},
        { "number": '6.',
          "group_name": 'BG1',
          "classification": 'Būvizstrādājumu galdnieks',
          "specialty": 'Kokizstrādājumu izgatavošana',
          "functions": ''},
        { "number": '7.',
          "group_name": 'DD1',
          "classification": 'Digitālās drukas operators',
          "specialty": 'Poligrāfija un izdevējdarbība',
          "functions": ''},
        { "number": '8.',
          "group_name": 'DK1-1',
          "classification": 'Datorsistēmu tehniķis',
          "specialty": 'Datorsistēmas, datu bāzes un datortīkli',
          "functions": ''},
        { "number": '9.',
          "group_name": 'DP1-1',
          "classification": 'Programmēšanas tehniķis',
          "specialty": 'Programmēšana',
          "functions": ''},
        { "number": '10.',
          "group_name": 'DP1-2',
          "classification": 'Programmēšanas tehniķis',
          "specialty": 'Programmēšana',
          "functions": ''},
        { "number": '11.',
          "group_name": 'DP1-3',
          "classification": 'Programmēšanas tehniķis',
          "specialty": 'Programmēšana',
          "functions": ''},
        { "number": '12.',
          "group_name": 'DP1-4',
          "classification": 'Programmēšanas tehniķis',
          "specialty": 'Programmēšana',
          "functions": ''},
        { "number": '13.',
          "group_name": 'DT1-1',
          "classification": 'Datorsistēmu tehniķis',
          "specialty": 'Datorsistēmas, datu bāzes un datortīkli',
          "functions": ''},
        { "number": '14.',
          "group_name": 'DT1-2',
          "classification": 'Datorsistēmu tehniķis',
          "specialty": 'Datorsistēmas, datu bāzes un datortīkli',
          "functions": ''},
        { "number": '15.',
          "group_name": 'EA1',
          "classification": 'Atjaunojamās enerģētikas tehniķis',
          "specialty": 'Enerģētika un elektrotehnika',
          "functions": ''},
        { "number": '16.',
          "group_name": 'ET1',
          "classification": 'Elektrotehniķis',
          "specialty": 'Enerģētika un elektrotehnika',
          "functions": ''},
        { "number": '17.',
          "group_name": 'G1',
          "classification": 'Grāmatvedis',
          "specialty": 'Grāmatvedība',
          "functions": ''},
        { "number": '18.',
          "group_name": 'GK1',
          "classification": 'Reklāmas pakalpojumu komercdarbinikes',
          "specialty": 'Komerczinības',
          "functions": ''},
        { "number": '19.',
          "group_name": 'GL1-1',
          "classification": 'Loģistikas darbinieks',
          "specialty": 'Telemehānika un loģistika',
          "functions": ''},
        { "number": '20.',
          "group_name": 'GL1-2',
          "classification": 'Loģistikas darbinieks',
          "specialty": 'Telemehānika un loģistika',
          "functions": ''},
        { "number": '21.',
          "group_name": 'KD1',
          "classification": 'Datorizētu kokapstrādes iekārtu operators',
          "specialty": 'Kokizstrādājumu izgatavošana',
          "functions": ''},
        { "number": '22.',
          "group_name": 'KT1',
          "classification": 'Koka izstrādājumu ražošanas tehniķis',
          "specialty": 'Kokizstrādājumu izgatavošana',
          "functions": ''},
        { "number": '23.',
          "group_name": 'L1',
          "classification": 'Lokomotīvju saimniecības tehniķis',
          "specialty": 'Dzelzceļa transports',
          "functions": ''},
        { "number": '24.',
          "group_name": 'M1',
          "classification": 'Mašīnbūves tehniķis',
          "specialty": 'Inženiermehānika, mehānika un mašīnbūves tehnoloģija',
          "functions": ''},
        { "number": '25.',
          "group_name": 'MG1',
          "classification": 'Mēbeļu galdnieks',
          "specialty": 'Kokizstrādājumu izgatavošana',
          "functions": ''},
        { "number": '26.',
          "group_name": 'N1',
          "classification": 'Iespieddarbu noformējuma tehniķis',
          "specialty": 'Poligrāfija un izdevējdarbība',
          "functions": ''},
        { "number": '27.',
          "group_name": 'PIT1',
          "classification": 'Poligrāfijas iekārtu tehniķis',
          "specialty": 'Poligrāfija un izdevējdarbība',
          "functions": ''},
        { "number": '28.',
          "group_name": 'PRT1',
          "classification": 'Poligrāfijas ražošanas tehniķis',
          "specialty": 'Poligrāfijas ražošanas tehnoloģijas un izstrādājumu izgatavošana',
          "functions": ''},
        { "number": '29.',
          "group_name": 'S1',
          "classification": 'Materiālu ķīmijas tehniķis',
          "specialty": 'Ķīmijas tehnoloģijas',
          "functions": ''},
        { "number": '30.',
          "group_name": 'TA1',
          "classification": 'Dzelzceļa transporta automātikas, telemehānikas un sakaru tehniķis',
          "specialty": 'Dzelzceļa pakalpojumi',
          "functions": ''},
        { "number": '31.',
          "group_name": 'TP1',
          "classification": 'Dzelzceļa transporta pārvadājumu organizācijas un kustības drošības tehniķis',
          "specialty": 'Dzelzceļa pakalpojumi',
          "functions": ''},
        { "number": '32.',
          "group_name": 'VA1',
          "classification": 'Automehāniķis',
          "specialty": 'Autotransports',
          "functions": ''},
        { "number": '33.',
          "group_name": 'VAV1',
          "classification": 'Autovirsbūvju remontatslēdznieks',
          "specialty": 'Autotransports',
          "functions": ''},
        { "number": '34.',
          "group_name": 'VB1',
          "classification": 'Klientu apkalpošanas speciālists',
          "specialty": 'Administratīvie un sekretāra pakalpojumi',
          "functions": ''},
        { "number": '35.',
          "group_name": 'VDD1',
          "classification": 'Digitālās drukas operators',
          "specialty": 'Poligrāfija un izdevējdarbība',
          "functions": ''},
        { "number": '36.',
          "group_name": 'VET1',
          "classification": 'Elektrotehniķis',
          "specialty": 'Enerģētika un elektrotehnika',
          "functions": ''},
        { "number": '37.',
          "group_name": 'VL1',
          "classification": 'Lietvedis',
          "specialty": 'Administratīvie un sekretāra pakalpojumi',
          "functions": ''},
        { "number": '38.',
          "group_name": 'VPIT1',
          "classification": 'Poligrāfijas iekārtu tehniķis',
          "specialty": 'Poligrāfija un izdevējdarbība',
          "functions": ''},
        { "number": '39.',
          "group_name": 'VPRT1',
          "classification": 'Poligrāfijas ražošanas tehniķis',
          "specialty": 'Poligrāfijas ražošanas tehnoloģijas un izstrādājumu izgatavošana',
          "functions": ''},
      ],

      selected: null,
      options: [
        { value: 'null', text: '-' },
        { text: '[pēc 9. klases] Administratīvie un sekretāra pakalpojumi - Klientu apkalpošanas speciālists' },
        { text: '[pēc 12. klases] Administratīvie un sekretāra pakalpojumi - Klientu apkalpošanas speciālists ' },
        { text: '[pēc 12. klases] Administratīvie un sekretāra pakalpojumi - Lietvedis ' },
        { text: '[pēc 9. klases] Autotransports - Automehāniķis ' },
        { text: '[pēc 12. klases] Autotransports - Autovirsbūvju remontatslēdznieks ' },
        { text: '[pēc 9. klases] Autotransports  - Transportlīdzekļu krāsotājs ' },
        { text: '[pēc 9. klases] Autotransports - Autovirsbūvju remontatslēdznieks ' },
        { text: '[pēc 9. klases] Datorsistēmas, datu bāzes un datortīkli  - Datorsistēmu tehniķis ' },
        { text: '[pēc 9. klases] Dzelzceļa pakalpojumi   - Dzelzceļa transporta automātikas, telemehānikas un sakaru tehniķis ' },
        { text: '[pēc 9. klases] Dzelzceļa pakalpojumi   - Dzelzceļa transporta pārvadājumu organizācijas un kustības drošības tehniķis ' },
        { text: '[pēc 9. klases] Dzelzceļa transports  - Lokomotīvju saimniecības tehniķis ' },
        { text: '[pēc 9. klases] Enerģētika un elektrotehnika - Elektrotehniķis ' },
        { text: '[pēc 12. klases] Enerģētika un elektrotehnika - Elektrotehniķis ' },
        { text: '[pēc 9. klases] Grāmatvedība - Grāmatvedis ' },
        { text: '[pēc 9. klases] Inženiermehānika, mehānika un mašīnbūves tehnoloģija - Mašīnbūves tehniķis ' },
        { text: '[pēc 9. klases] Ķīmijas tehnoloģijas - Materiālu ķīmijas tehniķis ' },
        { text: '[pēc 9. klases] Kokizstrādājumu izgatavošana   - Koka izstrādājumu ražošanas tehniķis ' },
        { text: '[pēc 9. klases] Kokizstrādājumu izgatavošana - Datorizētu kokapstrādes iekārtu operators ' },
        { text: '[pēc 9. klases] Kokizstrādājumu izgatavošana  - Būvizstrādājumu galdnieks ' },
        { text: '[pēc 9. klases] Kokizstrādājumu izgatavošana   - Mēbeļu galdnieks  ' },
        { text: '[pēc 9. klases] Komerczinības - Reklāmas pakalpojumu komercdarbinikes  ' },
        { text: '[pēc 9. klases] Poligrāfija un izdevējdarbība - Poligrāfijas iekārtu tehniķis ' },
        { text: '[pēc 12. klases] Poligrāfija un izdevējdarbība - Poligrāfijas iekārtu tehniķis ' },
        { text: '[pēc 12. klases] Poligrāfija un izdevējdarbība - Digitālās drukas operators ' },
        { text: '[pēc 9. klases] Poligrāfija un izdevējdarbība - Digitālās drukas operators ' },
        { text: '[pēc 9. klases] Poligrāfijas ražošanas tehnoloģijas un izstrādājumu izgatavošana - Poligrāfijas ražošanas tehniķis ' },
        { text: '[pēc 12. klases] Poligrāfijas ražošanas tehnoloģijas un izstrādājumu izgatavošana - Poligrāfijas ražošanas tehniķis ' },
        { text: '[pēc 9. klases] Programmēšana - Programmēšanas tehniķis ' },
        { text: '[pēc 9. klases] Telemehānika un loģistika - Loģistikas darbinieks ' }
      ]

    }
  }
}
</script>

<style scoped>

</style>